/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudyDeckIdRouteImport } from './routes/study.$deckId'
import { Route as DeepDeckIdRouteImport } from './routes/deep.$deckId'
import { Route as DeckDeckIdRouteImport } from './routes/deck.$deckId'
import { Route as TypeDeckIdRouteImport } from './routes/type.$deckId'
import { Route as BuilderDeckIdRouteImport } from './routes/builder.$deckId'
import { Route as BlankDeckIdRouteImport } from './routes/blank.$deckId'
import { Route as SpeedDeckIdRouteImport } from './routes/speed.$deckId'
import { Route as AssocDeckIdRouteImport } from './routes/assoc.$deckId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyDeckIdRoute = StudyDeckIdRouteImport.update({
  id: '/study/$deckId',
  path: '/study/$deckId',
  getParentRoute: () => rootRouteImport,
} as any)
const DeepDeckIdRoute = DeepDeckIdRouteImport.update({
  id: '/deep/$deckId',
  path: '/deep/$deckId',
  getParentRoute: () => rootRouteImport,
} as any)
const DeckDeckIdRoute = DeckDeckIdRouteImport.update({
  id: '/deck/$deckId',
  path: '/deck/$deckId',
  getParentRoute: () => rootRouteImport,
} as any)
const TypeDeckIdRoute = TypeDeckIdRouteImport.update({
  id: '/type/$deckId',
  path: '/type/$deckId',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderDeckIdRoute = BuilderDeckIdRouteImport.update({
  id: '/builder/$deckId',
  path: '/builder/$deckId',
  getParentRoute: () => rootRouteImport,
} as any)
const BlankDeckIdRoute = BlankDeckIdRouteImport.update({
  id: '/blank/$deckId',
  path: '/blank/$deckId',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeedDeckIdRoute = SpeedDeckIdRouteImport.update({
  id: '/speed/$deckId',
  path: '/speed/$deckId',
  getParentRoute: () => rootRouteImport,
} as any)
const AssocDeckIdRoute = AssocDeckIdRouteImport.update({
  id: '/assoc/$deckId',
  path: '/assoc/$deckId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/deck/$deckId': typeof DeckDeckIdRoute
  '/deep/$deckId': typeof DeepDeckIdRoute
  '/study/$deckId': typeof StudyDeckIdRoute
  '/type/$deckId': typeof TypeDeckIdRoute
  '/builder/$deckId': typeof BuilderDeckIdRoute
  '/blank/$deckId': typeof BlankDeckIdRoute
  '/speed/$deckId': typeof SpeedDeckIdRoute
  '/assoc/$deckId': typeof AssocDeckIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/deck/$deckId': typeof DeckDeckIdRoute
  '/deep/$deckId': typeof DeepDeckIdRoute
  '/study/$deckId': typeof StudyDeckIdRoute
  '/type/$deckId': typeof TypeDeckIdRoute
  '/builder/$deckId': typeof BuilderDeckIdRoute
  '/blank/$deckId': typeof BlankDeckIdRoute
  '/speed/$deckId': typeof SpeedDeckIdRoute
  '/assoc/$deckId': typeof AssocDeckIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/deck/$deckId': typeof DeckDeckIdRoute
  '/deep/$deckId': typeof DeepDeckIdRoute
  '/study/$deckId': typeof StudyDeckIdRoute
  '/type/$deckId': typeof TypeDeckIdRoute
  '/builder/$deckId': typeof BuilderDeckIdRoute
  '/blank/$deckId': typeof BlankDeckIdRoute
  '/speed/$deckId': typeof SpeedDeckIdRoute
  '/assoc/$deckId': typeof AssocDeckIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/deck/$deckId' | '/deep/$deckId' | '/study/$deckId' | '/type/$deckId' | '/builder/$deckId' | '/blank/$deckId' | '/speed/$deckId' | '/assoc/$deckId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/deck/$deckId' | '/deep/$deckId' | '/study/$deckId' | '/type/$deckId' | '/builder/$deckId' | '/blank/$deckId' | '/speed/$deckId' | '/assoc/$deckId'
  id: '__root__' | '/' | '/deck/$deckId' | '/deep/$deckId' | '/study/$deckId' | '/type/$deckId' | '/builder/$deckId' | '/blank/$deckId' | '/speed/$deckId' | '/assoc/$deckId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeckDeckIdRoute: typeof DeckDeckIdRoute
  DeepDeckIdRoute: typeof DeepDeckIdRoute
  StudyDeckIdRoute: typeof StudyDeckIdRoute
  TypeDeckIdRoute: typeof TypeDeckIdRoute
  BuilderDeckIdRoute: typeof BuilderDeckIdRoute
  BlankDeckIdRoute: typeof BlankDeckIdRoute
  SpeedDeckIdRoute: typeof SpeedDeckIdRoute
  AssocDeckIdRoute: typeof AssocDeckIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/$deckId': {
      id: '/study/$deckId'
      path: '/study/$deckId'
      fullPath: '/study/$deckId'
      preLoaderRoute: typeof StudyDeckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deep/$deckId': {
      id: '/deep/$deckId'
      path: '/deep/$deckId'
      fullPath: '/deep/$deckId'
      preLoaderRoute: typeof DeepDeckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deck/$deckId': {
      id: '/deck/$deckId'
      path: '/deck/$deckId'
      fullPath: '/deck/$deckId'
      preLoaderRoute: typeof DeckDeckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/type/$deckId': {
      id: '/type/$deckId'
      path: '/type/$deckId'
      fullPath: '/type/$deckId'
      preLoaderRoute: typeof TypeDeckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder/$deckId': {
      id: '/builder/$deckId'
      path: '/builder/$deckId'
      fullPath: '/builder/$deckId'
      preLoaderRoute: typeof BuilderDeckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blank/$deckId': {
      id: '/blank/$deckId'
      path: '/blank/$deckId'
      fullPath: '/blank/$deckId'
      preLoaderRoute: typeof BlankDeckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speed/$deckId': {
      id: '/speed/$deckId'
      path: '/speed/$deckId'
      fullPath: '/speed/$deckId'
      preLoaderRoute: typeof SpeedDeckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assoc/$deckId': {
      id: '/assoc/$deckId'
      path: '/assoc/$deckId'
      fullPath: '/assoc/$deckId'
      preLoaderRoute: typeof AssocDeckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeckDeckIdRoute: DeckDeckIdRoute,
  DeepDeckIdRoute: DeepDeckIdRoute,
  StudyDeckIdRoute: StudyDeckIdRoute,
  TypeDeckIdRoute: TypeDeckIdRoute,
  BuilderDeckIdRoute: BuilderDeckIdRoute,
  BlankDeckIdRoute: BlankDeckIdRoute,
  SpeedDeckIdRoute: SpeedDeckIdRoute,
  AssocDeckIdRoute: AssocDeckIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
