/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudyDeckIdRouteImport } from './routes/study.$deckId'
import { Route as DeepDeckIdRouteImport } from './routes/deep.$deckId'
import { Route as DeckDeckIdRouteImport } from './routes/deck.$deckId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyDeckIdRoute = StudyDeckIdRouteImport.update({
  id: '/study/$deckId',
  path: '/study/$deckId',
  getParentRoute: () => rootRouteImport,
} as any)
const DeepDeckIdRoute = DeepDeckIdRouteImport.update({
  id: '/deep/$deckId',
  path: '/deep/$deckId',
  getParentRoute: () => rootRouteImport,
} as any)
const DeckDeckIdRoute = DeckDeckIdRouteImport.update({
  id: '/deck/$deckId',
  path: '/deck/$deckId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/deck/$deckId': typeof DeckDeckIdRoute
  '/deep/$deckId': typeof DeepDeckIdRoute
  '/study/$deckId': typeof StudyDeckIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/deck/$deckId': typeof DeckDeckIdRoute
  '/deep/$deckId': typeof DeepDeckIdRoute
  '/study/$deckId': typeof StudyDeckIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/deck/$deckId': typeof DeckDeckIdRoute
  '/deep/$deckId': typeof DeepDeckIdRoute
  '/study/$deckId': typeof StudyDeckIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/deck/$deckId' | '/deep/$deckId' | '/study/$deckId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/deck/$deckId' | '/deep/$deckId' | '/study/$deckId'
  id: '__root__' | '/' | '/deck/$deckId' | '/deep/$deckId' | '/study/$deckId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeckDeckIdRoute: typeof DeckDeckIdRoute
  DeepDeckIdRoute: typeof DeepDeckIdRoute
  StudyDeckIdRoute: typeof StudyDeckIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/$deckId': {
      id: '/study/$deckId'
      path: '/study/$deckId'
      fullPath: '/study/$deckId'
      preLoaderRoute: typeof StudyDeckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deep/$deckId': {
      id: '/deep/$deckId'
      path: '/deep/$deckId'
      fullPath: '/deep/$deckId'
      preLoaderRoute: typeof DeepDeckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deck/$deckId': {
      id: '/deck/$deckId'
      path: '/deck/$deckId'
      fullPath: '/deck/$deckId'
      preLoaderRoute: typeof DeckDeckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeckDeckIdRoute: DeckDeckIdRoute,
  DeepDeckIdRoute: DeepDeckIdRoute,
  StudyDeckIdRoute: StudyDeckIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
