/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TypeDeckIdRouteImport } from './routes/type.$deckId'
import { Route as StudyDeckIdRouteImport } from './routes/study.$deckId'
import { Route as SpeedDeckIdRouteImport } from './routes/speed.$deckId'
import { Route as ReviewDeckIdRouteImport } from './routes/review.$deckId'
import { Route as ReverseDeckIdRouteImport } from './routes/reverse.$deckId'
import { Route as FeedbackDeckIdRouteImport } from './routes/feedback.$deckId'
import { Route as DeepDeckIdRouteImport } from './routes/deep.$deckId'
import { Route as DeckDeckIdRouteImport } from './routes/deck.$deckId'
import { Route as BuilderDeckIdRouteImport } from './routes/builder.$deckId'
import { Route as BlankDeckIdRouteImport } from './routes/blank.$deckId'
import { Route as AssocDeckIdRouteImport } from './routes/assoc.$deckId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TypeDeckIdRoute = TypeDeckIdRouteImport.update({
  id: '/type/$deckId',
  path: '/type/$deckId',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyDeckIdRoute = StudyDeckIdRouteImport.update({
  id: '/study/$deckId',
  path: '/study/$deckId',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeedDeckIdRoute = SpeedDeckIdRouteImport.update({
  id: '/speed/$deckId',
  path: '/speed/$deckId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewDeckIdRoute = ReviewDeckIdRouteImport.update({
  id: '/review/$deckId',
  path: '/review/$deckId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReverseDeckIdRoute = ReverseDeckIdRouteImport.update({
  id: '/reverse/$deckId',
  path: '/reverse/$deckId',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackDeckIdRoute = FeedbackDeckIdRouteImport.update({
  id: '/feedback/$deckId',
  path: '/feedback/$deckId',
  getParentRoute: () => rootRouteImport,
} as any)
const DeepDeckIdRoute = DeepDeckIdRouteImport.update({
  id: '/deep/$deckId',
  path: '/deep/$deckId',
  getParentRoute: () => rootRouteImport,
} as any)
const DeckDeckIdRoute = DeckDeckIdRouteImport.update({
  id: '/deck/$deckId',
  path: '/deck/$deckId',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderDeckIdRoute = BuilderDeckIdRouteImport.update({
  id: '/builder/$deckId',
  path: '/builder/$deckId',
  getParentRoute: () => rootRouteImport,
} as any)
const BlankDeckIdRoute = BlankDeckIdRouteImport.update({
  id: '/blank/$deckId',
  path: '/blank/$deckId',
  getParentRoute: () => rootRouteImport,
} as any)
const AssocDeckIdRoute = AssocDeckIdRouteImport.update({
  id: '/assoc/$deckId',
  path: '/assoc/$deckId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/assoc/$deckId': typeof AssocDeckIdRoute
  '/blank/$deckId': typeof BlankDeckIdRoute
  '/builder/$deckId': typeof BuilderDeckIdRoute
  '/deck/$deckId': typeof DeckDeckIdRoute
  '/deep/$deckId': typeof DeepDeckIdRoute
  '/feedback/$deckId': typeof FeedbackDeckIdRoute
  '/reverse/$deckId': typeof ReverseDeckIdRoute
  '/review/$deckId': typeof ReviewDeckIdRoute
  '/speed/$deckId': typeof SpeedDeckIdRoute
  '/study/$deckId': typeof StudyDeckIdRoute
  '/type/$deckId': typeof TypeDeckIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/assoc/$deckId': typeof AssocDeckIdRoute
  '/blank/$deckId': typeof BlankDeckIdRoute
  '/builder/$deckId': typeof BuilderDeckIdRoute
  '/deck/$deckId': typeof DeckDeckIdRoute
  '/deep/$deckId': typeof DeepDeckIdRoute
  '/feedback/$deckId': typeof FeedbackDeckIdRoute
  '/reverse/$deckId': typeof ReverseDeckIdRoute
  '/review/$deckId': typeof ReviewDeckIdRoute
  '/speed/$deckId': typeof SpeedDeckIdRoute
  '/study/$deckId': typeof StudyDeckIdRoute
  '/type/$deckId': typeof TypeDeckIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/assoc/$deckId': typeof AssocDeckIdRoute
  '/blank/$deckId': typeof BlankDeckIdRoute
  '/builder/$deckId': typeof BuilderDeckIdRoute
  '/deck/$deckId': typeof DeckDeckIdRoute
  '/deep/$deckId': typeof DeepDeckIdRoute
  '/feedback/$deckId': typeof FeedbackDeckIdRoute
  '/reverse/$deckId': typeof ReverseDeckIdRoute
  '/review/$deckId': typeof ReviewDeckIdRoute
  '/speed/$deckId': typeof SpeedDeckIdRoute
  '/study/$deckId': typeof StudyDeckIdRoute
  '/type/$deckId': typeof TypeDeckIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/assoc/$deckId'
    | '/blank/$deckId'
    | '/builder/$deckId'
    | '/deck/$deckId'
    | '/deep/$deckId'
    | '/feedback/$deckId'
    | '/reverse/$deckId'
    | '/review/$deckId'
    | '/speed/$deckId'
    | '/study/$deckId'
    | '/type/$deckId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/assoc/$deckId'
    | '/blank/$deckId'
    | '/builder/$deckId'
    | '/deck/$deckId'
    | '/deep/$deckId'
    | '/feedback/$deckId'
    | '/reverse/$deckId'
    | '/review/$deckId'
    | '/speed/$deckId'
    | '/study/$deckId'
    | '/type/$deckId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/reset-password'
    | '/assoc/$deckId'
    | '/blank/$deckId'
    | '/builder/$deckId'
    | '/deck/$deckId'
    | '/deep/$deckId'
    | '/feedback/$deckId'
    | '/reverse/$deckId'
    | '/review/$deckId'
    | '/speed/$deckId'
    | '/study/$deckId'
    | '/type/$deckId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AssocDeckIdRoute: typeof AssocDeckIdRoute
  BlankDeckIdRoute: typeof BlankDeckIdRoute
  BuilderDeckIdRoute: typeof BuilderDeckIdRoute
  DeckDeckIdRoute: typeof DeckDeckIdRoute
  DeepDeckIdRoute: typeof DeepDeckIdRoute
  FeedbackDeckIdRoute: typeof FeedbackDeckIdRoute
  ReverseDeckIdRoute: typeof ReverseDeckIdRoute
  ReviewDeckIdRoute: typeof ReviewDeckIdRoute
  SpeedDeckIdRoute: typeof SpeedDeckIdRoute
  StudyDeckIdRoute: typeof StudyDeckIdRoute
  TypeDeckIdRoute: typeof TypeDeckIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/type/$deckId': {
      id: '/type/$deckId'
      path: '/type/$deckId'
      fullPath: '/type/$deckId'
      preLoaderRoute: typeof TypeDeckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/$deckId': {
      id: '/study/$deckId'
      path: '/study/$deckId'
      fullPath: '/study/$deckId'
      preLoaderRoute: typeof StudyDeckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speed/$deckId': {
      id: '/speed/$deckId'
      path: '/speed/$deckId'
      fullPath: '/speed/$deckId'
      preLoaderRoute: typeof SpeedDeckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/$deckId': {
      id: '/review/$deckId'
      path: '/review/$deckId'
      fullPath: '/review/$deckId'
      preLoaderRoute: typeof ReviewDeckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reverse/$deckId': {
      id: '/reverse/$deckId'
      path: '/reverse/$deckId'
      fullPath: '/reverse/$deckId'
      preLoaderRoute: typeof ReverseDeckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback/$deckId': {
      id: '/feedback/$deckId'
      path: '/feedback/$deckId'
      fullPath: '/feedback/$deckId'
      preLoaderRoute: typeof FeedbackDeckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deep/$deckId': {
      id: '/deep/$deckId'
      path: '/deep/$deckId'
      fullPath: '/deep/$deckId'
      preLoaderRoute: typeof DeepDeckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deck/$deckId': {
      id: '/deck/$deckId'
      path: '/deck/$deckId'
      fullPath: '/deck/$deckId'
      preLoaderRoute: typeof DeckDeckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder/$deckId': {
      id: '/builder/$deckId'
      path: '/builder/$deckId'
      fullPath: '/builder/$deckId'
      preLoaderRoute: typeof BuilderDeckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blank/$deckId': {
      id: '/blank/$deckId'
      path: '/blank/$deckId'
      fullPath: '/blank/$deckId'
      preLoaderRoute: typeof BlankDeckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assoc/$deckId': {
      id: '/assoc/$deckId'
      path: '/assoc/$deckId'
      fullPath: '/assoc/$deckId'
      preLoaderRoute: typeof AssocDeckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AssocDeckIdRoute: AssocDeckIdRoute,
  BlankDeckIdRoute: BlankDeckIdRoute,
  BuilderDeckIdRoute: BuilderDeckIdRoute,
  DeckDeckIdRoute: DeckDeckIdRoute,
  DeepDeckIdRoute: DeepDeckIdRoute,
  FeedbackDeckIdRoute: FeedbackDeckIdRoute,
  ReverseDeckIdRoute: ReverseDeckIdRoute,
  ReviewDeckIdRoute: ReviewDeckIdRoute,
  SpeedDeckIdRoute: SpeedDeckIdRoute,
  StudyDeckIdRoute: StudyDeckIdRoute,
  TypeDeckIdRoute: TypeDeckIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
