// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { getRequest } from "@tanstack/react-start/server";
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { AuthTokenError, verifySupabaseAuthorization } from "./auth-token";
import { httpError } from "@/lib/server-http-error";

export const requireSupabaseAuth = createMiddleware({ type: "function" }).server(
  async ({ next }) => {
    const SUPABASE_URL = process.env.SUPABASE_URL || process.env.VITE_SUPABASE_URL;
    const SUPABASE_PUBLISHABLE_KEY =
      process.env.SUPABASE_PUBLISHABLE_KEY || process.env.VITE_SUPABASE_PUBLISHABLE_KEY;

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      const missing = [
        ...(!SUPABASE_URL ? ["SUPABASE_URL or VITE_SUPABASE_URL"] : []),
        ...(!SUPABASE_PUBLISHABLE_KEY
          ? ["SUPABASE_PUBLISHABLE_KEY or VITE_SUPABASE_PUBLISHABLE_KEY"]
          : []),
      ];
      console.error(
        `[Supabase] Missing server authentication configuration: ${missing.join(", ")}.`,
      );
      httpError(500, "AUTH_CONFIGURATION_ERROR", "Authentication is temporarily unavailable.");
    }

    const request = getRequest();

    if (!request?.headers) {
      httpError(401, "AUTH_REQUIRED", "Please sign in to continue.");
    }

    const contentLength = Number(request.headers.get("content-length") ?? "0");
    if (Number.isFinite(contentLength) && contentLength > 3_750_000) {
      httpError(413, "REQUEST_TOO_LARGE", "This request is too large.");
    }

    const authClient = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: undefined,
        persistSession: false,
        autoRefreshToken: false,
      },
    });

    let auth: Awaited<ReturnType<typeof verifySupabaseAuthorization>>;
    try {
      auth = await verifySupabaseAuthorization(
        request.headers.get("authorization"),
        async (token) => authClient.auth.getClaims(token),
      );
    } catch (error) {
      if (error instanceof AuthTokenError) {
        httpError(401, error.code, error.message);
      }
      throw error;
    }

    const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      global: { headers: { Authorization: `Bearer ${auth.token}` } },
      auth: {
        storage: undefined,
        persistSession: false,
        autoRefreshToken: false,
      },
    });

    return next({
      context: {
        supabase,
        userId: auth.userId,
        claims: auth.claims,
      },
    });
  },
);
